import { describe, expect, it, vi, afterEach } from "vitest";
import { REDACTED, redact, reportServerError, reportServerWarning } from "./report";
import { generateLinkToken, hashLinkToken } from "@/lib/security/tokens";

/**
 * Logging that cannot leak.
 *
 * Driplin had no logging, which was safe and unhelpful. Adding it is where
 * products acquire a log aggregator full of API keys, link tokens and
 * customers' addresses — held in a system with weaker access control than
 * the database the data came from, and kept for longer.
 *
 * These tests exist because "we are careful about what we log" is not a
 * control. The redaction is, so it is tested against the real shapes this
 * codebase produces.
 */

afterEach(() => vi.restoreAllMocks());

function captured(fn: () => void): Record<string, unknown> {
  // Restore first: spying on an already-spied method returns the existing
  // spy, so a second call in one test would otherwise read the first
  // entry back.
  vi.restoreAllMocks();
  const spy = vi.spyOn(console, "error").mockImplementation(() => {});
  const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
  fn();
  const line = (spy.mock.calls[0]?.[0] ?? warn.mock.calls[0]?.[0]) as string;
  return JSON.parse(line);
}

describe("secrets never reach the output", () => {
  it("redacts a real link token", () => {
    // Generated by the same function that mints board and vendor links.
    const token = generateLinkToken();
    expect(redact(token)).toBe(REDACTED);
  });

  it("redacts a real token hash, which identifies a token", () => {
    expect(redact(hashLinkToken("anything"))).toBe(REDACTED);
  });

  it("redacts Driplin's encrypted-credential envelope", () => {
    expect(redact("v1.aGVsbG8.dGFnZ2Vk.Y2lwaGVydGV4dA")).toBe(REDACTED);
  });

  it("redacts a JWT, which is what a Supabase key looks like", () => {
    expect(
      redact("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIn0.sig")
    ).toBe(REDACTED);
  });

  it("redacts a Bearer header value", () => {
    expect(redact("Bearer sk_live_abcdefghijklmnop")).toBe(REDACTED);
  });

  it.each([
    "token",
    "api_key",
    "apiKey",
    "Authorization",
    "cookie",
    "CRON_SECRET",
    "password",
    "vendor_credential",
    "service_role_key",
    "key",
  ])("redacts anything under the key %o, whatever its value", (key) => {
    const out = redact({ [key]: "totally-innocent-looking" }) as Record<string, unknown>;
    expect(out[key]).toBe(REDACTED);
  });

  it("reaches secrets nested inside objects and arrays", () => {
    const out = redact({
      vendors: [{ name: "Hill Country Lawn", api_key: "secret-value" }],
      nested: { deeper: { token: "secret-value" } },
    }) as Record<string, unknown>;
    const vendors = out.vendors as Record<string, unknown>[];
    expect(vendors[0].api_key).toBe(REDACTED);
    expect(vendors[0].name).toBe("Hill Country Lawn");
    expect(
      ((out.nested as Record<string, unknown>).deeper as Record<string, unknown>).token
    ).toBe(REDACTED);
  });
});

describe("personal data", () => {
  it("masks an email but keeps the domain, which is what diagnoses delivery", () => {
    expect(redact("dana.reed@hillcountrypm.com")).toBe("d***@hillcountrypm.com");
  });

  it("masks an email held under an innocuous key", () => {
    const out = redact({ recipient: "dana@example.com" }) as Record<string, unknown>;
    expect(out.recipient).toBe("d***@example.com");
  });
});

describe("staying small", () => {
  it("truncates a long string rather than dumping it", () => {
    const out = redact("x".repeat(1000)) as string;
    expect(out.length).toBeLessThan(400);
    expect(out).toContain("1000 chars");
  });

  it("caps an array and says how much it dropped", () => {
    const out = redact(Array.from({ length: 50 }, (_, i) => i)) as unknown[];
    expect(out.length).toBeLessThanOrEqual(21);
    expect(String(out[out.length - 1])).toContain("more");
  });

  it("stops recursing rather than following a deep structure forever", () => {
    let deep: Record<string, unknown> = { value: "bottom" };
    for (let i = 0; i < 12; i++) deep = { nested: deep };
    expect(JSON.stringify(redact(deep))).toContain("too deep");
  });

  it("survives a circular reference", () => {
    const a: Record<string, unknown> = { name: "a" };
    a.self = a;
    expect(() => JSON.stringify(redact(a))).not.toThrow();
  });
});

describe("the entry that gets written", () => {
  it("names the event, so a failure can be searched for", () => {
    const entry = captured(() =>
      reportServerError("controller.sync_failed", new Error("Rachio returned 403"), {
        controllerId: "ctrl-1",
        vendor: "rachio",
      })
    );
    expect(entry.event).toBe("controller.sync_failed");
    expect(entry.message).toBe("Rachio returned 403");
    expect((entry.context as Record<string, unknown>).vendor).toBe("rachio");
    expect(entry.level).toBe("error");
    expect(typeof entry.at).toBe("string");
  });

  it("redacts a secret that slipped into the error message itself", () => {
    // A vendor SDK echoing the key back in its error text is exactly how
    // this happens in practice.
    const entry = captured(() =>
      reportServerError("x", new Error("Bearer sk_live_abcdefghijklmnop"))
    );
    expect(entry.message).toBe(REDACTED);
  });

  it("redacts context even when the caller passes something careless", () => {
    const entry = captured(() =>
      reportServerError("x", new Error("boom"), { api_key: "live-key" })
    );
    expect((entry.context as Record<string, unknown>).api_key).toBe(REDACTED);
  });

  it("copes with something thrown that is not an Error", () => {
    const entry = captured(() => reportServerError("x", "just a string"));
    expect(entry.message).toBe("just a string");
    const other = captured(() => reportServerError("x", { weird: true }));
    expect(other.message).toBe("Unknown error");
  });

  it("writes a warning at warn level", () => {
    const entry = captured(() => reportServerWarning("x", "nothing broken yet"));
    expect(entry.level).toBe("warn");
  });

  it("emits valid single-line JSON", () => {
    const spy = vi.spyOn(console, "error").mockImplementation(() => {});
    reportServerError("x", new Error("multi\nline"), { note: "a,b" });
    const line = spy.mock.calls[0][0] as string;
    expect(line.split("\n")).toHaveLength(1);
    expect(() => JSON.parse(line)).not.toThrow();
  });
});
